"""add uniques to venue

Revision ID: 15e58cee6c6e
Revises: 0ea6d14c0ffa
Create Date: 2020-08-11 04:28:06.108697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e58cee6c6e'
down_revision = '0ea6d14c0ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'venue', ['address'])
    op.create_unique_constraint(None, 'venue', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue', type_='unique')
    op.drop_constraint(None, 'venue', type_='unique')
    # ### end Alembic commands ###
