"""deleted changes to show migration use

Revision ID: 92d5ae24569d
Revises: 5b616305f580
Create Date: 2020-08-11 00:56:38.786368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92d5ae24569d'
down_revision = '5b616305f580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show')
    op.drop_column('artist', 'website')
    op.drop_column('artist', 'seeking_venue')
    op.drop_column('artist', 'seeking_description')
    op.drop_column('venue', 'website')
    op.drop_column('venue', 'seeking_description')
    op.drop_column('venue', 'genres')
    op.drop_column('venue', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('seeking_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('seeking_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('show',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], [u'artist.id'], name=u'show_artist_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], [u'venue.id'], name=u'show_venue_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'show_pkey')
    )
    # ### end Alembic commands ###
