"""add default value to seeking talent or venue

Revision ID: f61ecd3ff531
Revises: 15e58cee6c6e
Create Date: 2020-08-11 10:44:04.762982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f61ecd3ff531'
down_revision = '15e58cee6c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'seeking_venue',
               existing_type=sa.BOOLEAN())
    op.alter_column('venue', 'seeking_talent',
               existing_type=sa.BOOLEAN())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'seeking_talent',
               existing_type=sa.BOOLEAN())
    op.alter_column('artist', 'seeking_venue',
               existing_type=sa.BOOLEAN())
    # ### end Alembic commands ###
